# H2 Database
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:fooddatabase
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.thymeleaf.check-template=true
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

spring.thymeleaf.cache=false

